stages:
  - build
  - test
  
cache:
  untracked: true
  paths:
    - ./node_modules/

#UI BUILD
ui Build:
  stage: build
  script:
    - yarn install
    - yarn build
#UI BUILD

#UI Unit Test
ui tests:
  stage: test
  script:
    - yarn test
#UI End Test